apiVersion: apps/v1
kind: Deployment
metadata:
  name: goo
  namespace: goo-prod
  labels: { app: goo }
spec:
  replicas: 1
  selector:
    matchLabels: { app: goo }
  template:
    metadata:
      labels: { app: goo }
    spec:
      containers:
        - name: goo
          image: ghcr.io/ogrodje/goo:0.0.6
          ports: [ { containerPort: 7777 }, { containerPort: 7778 } ]
          env:
            - { name: GOO_ENVIRONMENT, value: "Production" }
            - { name: PORT, value: "7777" }
            - { name: OTEL_TRACES_EXPORTER, value: "none" }
            - { name: OTEL_METRICS_EXPORTER, value: "none" }
            - { name: OTEL_LOGS_EXPORTER, value: "none" }
            - { name: POSTGRES_DB, value: "goo" }
            - { name: POSTGRES_HOST, value: "pg-one-postgresql.goo-prod.svc.cluster.local" }
            - { name: POSTGRES_PORT, value: "5432" }
            - { name: POSTGRES_USER, value: "goo" }
            - { name: SOURCES, value: "All" }

            - { name: KEYCLOAK_ENDPOINT, value: "https://keycloak.ogrodje.si" }
            - { name: KEYCLOAK_REALM, value: "Ogrodje" }

            - name: SENTRY_AUTH_TOKEN
              valueFrom:
                secretKeyRef: { name: goo-secret, key: sentry_auth_token }

            - name: HYGRAPH_ENDPOINT
              valueFrom:
                secretKeyRef: { name: goo-secret, key: hygraph_endpoint }

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: pg-one-postgresql, key: password }
          volumeMounts:
            - name: playwright-cache
              mountPath: /root/.cache/ms-playwright
          livenessProbe:
            httpGet:
              path: /
              port: 7777
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 7777
            initialDelaySeconds: 20
            periodSeconds: 50

      volumes:
        - name: playwright-cache
          persistentVolumeClaim:
            claimName: playwright-cache-pvc
