apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goo-short-ingress
  namespace: goo-prod
  labels:
    version: "1"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: *";
      more_set_headers "Access-Control-Allow-Methods: *";
      more_set_headers "Access-Control-Allow-Headers: *";
      more_set_headers "Access-Control-Expose-Headers: Content-Length,Content-Range";
spec:
  ingressClassName: nginx
  rules:
    - host: goo.ogrodje.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goo-service
                port: { number: 80 }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: goo-prod
  labels: { version: "1" }
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak.ogrodje.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port: { number: 80 }