apiVersion: v1
kind: Service
metadata:
  name: goo-service
  namespace: goo-prod
  labels: { app: goo }
spec:
  selector: { app: goo }
  ports:
    - name: http
      port: 80
      targetPort: 7777
    - name: metrics
      port: 7778
      targetPort: 7778
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: goo-prod
spec:
  selector: { app: keycloak }
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goo
  namespace: goo-prod
  labels: { release: prom }
spec:
  selector:
    matchLabels: { app: goo }
  namespaceSelector:
    matchNames: [ goo-prod ]
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s